import React, { useState, useEffect } from 'react'
import { Loader, Card, FormField} from '../components'


const Home = () => {
    const [loading, setLoading] = useState(false) // USESTATE HOOK: 
    const [allPosts, setAllPosts] = useState(null)

    const [searchText, setSearchText] = useState('')

    //function there the picture is rendered
    const RenderCards = ({ data, title}) => { 
      if(data?.length > 0 ){
       return data.map((post) => <Card key={post._id} {...post}/>) //what spread operator does here is taking objects and arrange (to individual card) it accordingly without extra method
      } 

      return (
        <h2 className='mt-5 font-bold text-[#6449ff] text-xl uppercase'>{title}</h2>
      )

    }
  return (
    <section className='max-w-7xl mx-auto'>
      <div>
        <h1 className='font-extrabold text-[#222328] text-[32px]'>The community showcase</h1>
        <p className='mt-2 text-[#666e75] text-[14px] max-w[500px]'>Browse through the collection generated by Dall-E</p>        
      </div>
      
      <div className='mt-16'>
        <FormField />
      </div>

      <div className='mt-10'>
        {loading ? (  /* if it is loading */
          <div className='flex justify-center items-center'>
            <Loader />
          </div>

        ) : (

          <>
            {searchText && (
              <h2 className='font-medium text-[#666e75] text-xl mb-3'>
                Showing Result for <span className='text-[#222328]'>{searchText}</span>
              </h2>
            )}
            <div className='grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 '> {/* this where the cards or the pictures shown in the page */}
              {searchText ? (
                <RenderCards
                  data={[]}
                  title="no search result found"
                  />
              ):(
                <RenderCards 
                   data={[]}
                   title="no post found"
                />
                )
              }
            </div>
          </>

        )
      }
      </div>
    
    </section>
  )
}

export default Home